export const commands = {
    START:          'start',
    MIRRORTAR:      'tarmirror|tarmirror@EdithTar1Bot',
    MIRROR:         'mirror|mirror@EdithTar1Bot',
    MIRROR_STATUS:  'status|status@EdithTar1Bot',
    LIST:           'list|list@EdithTar1Bot',
    GET_FOLDER:     'getFolder|gf',
    CANCEL_MIRROR:  'cancel|cancel@EdithTar1Bot',
    CANCEL_ALL:     'cancelAll|ca',
    STATS:          'stats',
    GET_LINK:       'getLink|gl',
    CLONE:          'clone|clone@EdithTar1Bot',
    ID:             'id',
    MF:             'mf',
    TAR:            'tar|tar@EdithTar1Bot',
    UNZIP_MIRROR:   'unzipmirror|unzipmirror@EdithTar1Bot',
    COUT:           'count|count@EdithTar1Bot',
    HELP:           'help|help@EdithTar1Bot',
    AUTHORIZE:      'authorize|a',
    UNAUTHORIZE:    'unauthorize|ua',
    RESTART:        'restart|r',
    YTDL:           'ytdl|ytdl@EdithTar1Bot'
};

export const commandsAfter: any = {
    START:          '$',
    MIRRORTAR:      '($| (.+))',
    MIRROR:         '($| (.+))',
    MIRROR_STATUS:  '$',
    LIST:           ' (.+)',
    GET_FOLDER:     '$',
    CANCEL_MIRROR:  '($| (.+))',
    CANCEL_ALL:     '$',
    STATS:          '$',
    GET_LINK:       ' (.+)',
    CLONE:          ' (.+)',
    ID:             '$',
    MF:             '$',
    TAR:            ' (.+)',
    UNZIP_MIRROR:   ' (.+)',
    COUT:           ' (.+)',
    HELP:           '$',
    AUTHORIZE:      '$',
    UNAUTHORIZE:    '$',
    RESTART:        '$',
    YTDL:           '($| (.+))'
};
